(ns skein.mixin.codegen-test
  "The generated bytecode, exercised for real: classes are defined into
  a DynamicClassLoader and their static injector methods invoked — the
  full chain through SkeinHooks and the handler var included. (Instance
  injectors go through the same emit paths; their live proof is the
  example mod's mixin on a running server.)"
  (:require [clojure.string :as str]
            [clojure.test :refer [deftest is]]
            [skein.mixin.codegen :as codegen])
  (:import (clojure.lang DynamicClassLoader)
           (org.objectweb.asm ClassReader ClassVisitor MethodVisitor Opcodes)
           (org.spongepowered.asm.mixin.injection.callback CallbackInfo CallbackInfoReturnable)))

;;; Handlers the generated classes call (through their vars)

(def inject-calls (atom []))

(defn record-inject [message ci]
  (swap! inject-calls conj [message ci])
  :ignored)

(defn double-arg [x]
  (int (* 2 x)))

(defn upcase-return [value]
  (str/upper-case value))

;;; Helpers

(defn- load-class ^Class [^String class-name ^bytes bytecode]
  (.defineClass (DynamicClassLoader. (.getClassLoader clojure.lang.RT))
                class-name bytecode nil))

(defn- static-method ^java.lang.reflect.Method [^Class c ^String n param-types]
  (doto (.getDeclaredMethod c n (into-array Class param-types))
    (.setAccessible true)))

;;; :inject — static void target; the generated method must pass the
;;; params and the CallbackInfo through to the handler and discard the
;;; result.

(def ^:private inject-declaration
  {:target "java.lang.String"
   :class "skein.gen.InjectFixture"
   :injects [{:type :inject
              :method {:name "log" :desc "(Ljava/lang/String;)V" :static true
                       :param-descs ["Ljava/lang/String;"] :return-desc "V"}
              :at {:value "HEAD"}
              :cancellable false
              :handler "skein.mixin.codegen-test/record-inject"}]})

(deftest inject-calls-the-handler-var
  (let [c (load-class "skein.gen.InjectFixture" (codegen/generate-class inject-declaration))
        m (static-method c "skein$log$0" [String CallbackInfo])]
    (reset! inject-calls [])
    (.invoke m nil (object-array ["hello" nil]))
    (is (= [["hello" nil]] @inject-calls))))

;;; :modify-arg — the generated method takes the argument, hands it to
;;; the handler and returns the (unboxed) replacement.

(def ^:private modify-arg-declaration
  {:target "java.lang.String"
   :class "skein.gen.ModifyArgFixture"
   :injects [{:type :modify-arg
              :method {:name "compute" :desc "(I)I" :static true
                       :param-descs ["I"] :return-desc "I"}
              :at {:value "INVOKE"
                   :target "Ljava/lang/String;valueOf(I)Ljava/lang/String;"}
              :index 0
              :arg-desc "I"
              :handler "skein.mixin.codegen-test/double-arg"}]})

(deftest modify-arg-boxes-unboxes-and-replaces
  (let [c (load-class "skein.gen.ModifyArgFixture" (codegen/generate-class modify-arg-declaration))
        m (static-method c "skein$compute$0" [Integer/TYPE])]
    (is (= 42 (.invoke m nil (object-array [(int 21)]))))))

;;; :modify-return — an @Inject at RETURN driving a real
;;; CallbackInfoReturnable: the handler's result becomes the return
;;; value (setReturnValue also cancels).

(def ^:private modify-return-declaration
  {:target "java.lang.String"
   :class "skein.gen.ModifyReturnFixture"
   :injects [{:type :modify-return
              :method {:name "motd" :desc "()Ljava/lang/String;" :static true
                       :param-descs [] :return-desc "Ljava/lang/String;"}
              :handler "skein.mixin.codegen-test/upcase-return"}]})

(deftest modify-return-replaces-through-the-callback
  (let [c (load-class "skein.gen.ModifyReturnFixture"
                      (codegen/generate-class modify-return-declaration))
        m (static-method c "skein$motd$0" [CallbackInfoReturnable])
        cir (CallbackInfoReturnable. "motd" true "original")]
    (.invoke m nil (object-array [cir]))
    (is (= "ORIGINAL" (.getReturnValue cir)))
    (is (true? (.isCancelled cir)))))

;;; Annotation structure — each annotation must land in the table
;;; matching its retention: @Mixin is CLASS retention (invisible),
;;; the injector annotations are RUNTIME retention (visible). A slip
;;; either way makes the mixin silently inert: the class merges but no
;;; callback is ever injected (defaultRequire only guards annotations
;;; the processor actually saw).

(defn- read-annotations [^bytes bytecode]
  (let [found (atom {:class [] :methods {}})]
    (.accept (ClassReader. bytecode)
             (proxy [ClassVisitor] [Opcodes/ASM9]
               (visitAnnotation [desc visible]
                 (swap! found update :class conj [desc visible])
                 nil)
               (visitMethod [_access method-name _desc _signature _exceptions]
                 (proxy [MethodVisitor] [Opcodes/ASM9]
                   (visitAnnotation [desc visible]
                     (swap! found update-in [:methods method-name] (fnil conj []) [desc visible])
                     nil))))
             0)
    @found))

(deftest annotations-land-in-the-tables-matching-their-retention
  (let [inject-ann (read-annotations (codegen/generate-class inject-declaration))
        modify-arg-ann (read-annotations (codegen/generate-class modify-arg-declaration))]
    (is (= [["Lorg/spongepowered/asm/mixin/Mixin;" false]] (:class inject-ann)))
    (is (= [["Lorg/spongepowered/asm/mixin/injection/Inject;" true]]
           (get-in inject-ann [:methods "skein$log$0"])))
    (is (= [["Lorg/spongepowered/asm/mixin/injection/ModifyArg;" true]]
           (get-in modify-arg-ann [:methods "skein$compute$0"])))))
