// core-lib — a separate artifact mods depend on:
// registry DSL, event wrappers registering vars (hot reload), interop helpers.
plugins {
    `java-library`
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

dependencies {
    implementation(libs.clojure)
    // M4: compileOnly fabric-api / game classes via Loom for event wrappers.

    // The mixin build pipeline's unit tests run it the way the compile fork
    // sees it: ASM + sponge-mixin stand in for the loader libraries Loom puts
    // on every dev classpath, malli is what the Skein plugin injects for
    // mixins.edn validation, and :runtime provides SkeinHooks for the
    // generated bytecode to call.
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platform.launcher)
    testImplementation(libs.asm)
    testImplementation(libs.sponge.mixin)
    testImplementation(libs.malli)
    testRuntimeOnly(project(":runtime"))
    testRuntimeOnly(libs.slf4j)
}

sourceSets.main {
    resources.srcDir("src/main/clojure")
}

// The Clojure test namespaces load from source in the test JVM.
sourceSets.test {
    resources.srcDir("src/test/clojure")
}

tasks.test {
    useJUnitPlatform()
}
