// core-lib — a separate artifact mods depend on:
// registry DSL, event wrappers registering vars (hot reload), interop helpers.
plugins {
    `java-library`
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

// The deobfuscated Minecraft jar and its libraries, as Loom resolves them for
// example-mod, minus the Skein project jars. example-mod resolves its own
// runtime classpath in its own build (Gradle 9 forbids resolving another
// project's configuration during this one's resolution) and writes the paths to
// a file; the test task depends on that task and reads the file here. This
// module needs no Loom of its own.
val gameClasspathFile = file("${project(":example-mod").projectDir}/build/skein-game-classpath.txt")
val gameClasspath = files(provider {
    if (gameClasspathFile.exists()) gameClasspathFile.readLines().filter { it.isNotBlank() } else emptyList()
})

dependencies {
    implementation(libs.clojure)
    // M4: compileOnly fabric-api / game classes via Loom for event wrappers.

    // The mixin build pipeline's unit tests run it the way the compile fork
    // sees it: ASM + sponge-mixin stand in for the loader libraries Loom puts
    // on every dev classpath, malli is what the Skein plugin injects for
    // mixins.edn validation, and :runtime provides SkeinHooks for the
    // generated bytecode to call.
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platform.launcher)
    testImplementation(libs.asm)
    testImplementation(libs.sponge.mixin)
    testImplementation(libs.malli)
    testRuntimeOnly(project(":runtime"))
    testRuntimeOnly(libs.slf4j)

    // The FP API layer's L1 coercion (skein.id/pos/text) turns data into real
    // game types (Identifier, BlockPos, Vec3, Component). Its unit tests build
    // those objects without booting the game, so the deobfuscated Minecraft jar
    // and the library set it links against must be on the test runtime
    // classpath. Loom resolves exactly that set for example-mod; reuse it here,
    // minus the Skein project jars — this module's own Clojure sources load from
    // its resources, and pulling the built jars back in would be circular.
    testRuntimeOnly(gameClasspath)
}

sourceSets.main {
    resources.srcDir("src/main/clojure")
}

// The Clojure test namespaces load from source in the test JVM.
sourceSets.test {
    resources.srcDir("src/test/clojure")
}

tasks.test {
    useJUnitPlatform()
    // example-mod (which applies Loom) resolves and writes the game classpath.
    dependsOn(":example-mod:exportGameClasspath")
    // MC 26.x classes are Java 25 bytecode; the toolchain above already targets 25.
}
