// core-lib — a separate artifact mods depend on:
// registry DSL, event wrappers registering vars (hot reload), interop helpers.
plugins {
    `java-library`
    `maven-publish`
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
    // Ships as Clojure sources anyway (the .clj tree is packed as resources
    // below), but a standard -sources jar keeps Maven tooling happy.
    withSourcesJar()
}

// The deobfuscated Minecraft jar and its libraries, as Loom resolves them for
// example-mod, minus the Skein project jars. example-mod resolves its own
// runtime classpath in its own build (Gradle 9 forbids resolving another
// project's configuration during this one's resolution) and writes the paths to
// a file; the test task depends on that task and reads the file here. This
// module needs no Loom of its own.
val gameClasspathFile = file("${project(":example-mod").projectDir}/build/skein-game-classpath.txt")
val gameClasspath = files(provider {
    if (gameClasspathFile.exists()) gameClasspathFile.readLines().filter { it.isNotBlank() } else emptyList()
})

dependencies {
    implementation(libs.clojure)
    // The FP layer's boundary schema validation (skein.schema and the item/
    // blockstate/register!/command schemas) and its logging bridge (skein.log).
    // The adapter bundles all three for the whole JVM; a mod gets them on its
    // classpath from the Skein Gradle plugin, so — like Clojure — they are a
    // runtime dependency of this artifact, not something a mod spells out.
    implementation(libs.malli)
    implementation(libs.tools.logging)
    runtimeOnly(libs.dynaload)
    // M4: compileOnly fabric-api / game classes via Loom for event wrappers.

    // The mixin build pipeline's unit tests run it the way the compile fork
    // sees it: ASM + sponge-mixin stand in for the loader libraries Loom puts
    // on every dev classpath, and :runtime provides SkeinHooks for the
    // generated bytecode to call.
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly(libs.junit.platform.launcher)
    testImplementation(libs.asm)
    testImplementation(libs.sponge.mixin)
    testRuntimeOnly(project(":runtime"))
    testRuntimeOnly(libs.slf4j)

    // The FP API layer's L1 coercion (skein.id/pos/text) turns data into real
    // game types (Identifier, BlockPos, Vec3, Component). Its unit tests build
    // those objects without booting the game, so the deobfuscated Minecraft jar
    // and the library set it links against must be on the test runtime
    // classpath. Loom resolves exactly that set for example-mod; reuse it here,
    // minus the Skein project jars — this module's own Clojure sources load from
    // its resources, and pulling the built jars back in would be circular.
    testRuntimeOnly(gameClasspath)
}

sourceSets.main {
    resources.srcDir("src/main/clojure")
}

// The Clojure test namespaces load from source in the test JVM.
sourceSets.test {
    resources.srcDir("src/test/clojure")
}

tasks.test {
    useJUnitPlatform()
    // example-mod (which applies Loom) resolves and writes the game classpath.
    dependsOn(":example-mod:exportGameClasspath")
    // MC 26.x classes are Java 25 bytecode; the toolchain above already targets 25.
}

// The FP API layer mods compile against — the primary Clojure artifact a modder
// writes `io.github.bondiano/skein` for. Publishes the jar (Clojure sources inside) plus
// a -sources jar; the group and base version come from the root gradle.properties.
publishing {
    publications {
        create<MavenPublication>("maven") {
            artifactId = "skein"
            from(components["java"])
            pom {
                name = "Skein"
                description = "Idiomatic Clojure API for Fabric mods — registry DSL, events, " +
                    "the functional world/command/text layer, and defmixin."
                url = "https://github.com/bondiano/skein"
                licenses {
                    license {
                        name = "MIT License"
                        url = "https://opensource.org/licenses/MIT"
                    }
                }
                developers {
                    developer {
                        id = "bondiano"
                        name = "bondiano"
                    }
                }
                scm {
                    url = "https://github.com/bondiano/skein"
                    connection = "scm:git:https://github.com/bondiano/skein.git"
                    developerConnection = "scm:git:ssh://git@github.com/bondiano/skein.git"
                }
            }
        }
    }
    repositories {
        // Clojars deploy: pass -PclojarsUsername / -PclojarsPassword (a deploy
        // token) or CLOJARS_USERNAME / CLOJARS_PASSWORD in the environment.
        // `publishToMavenLocal` needs no credentials and is how CI/dev verify.
        maven {
            name = "Clojars"
            url = uri("https://repo.clojars.org")
            credentials {
                username = (providers.gradleProperty("clojarsUsername")
                    .orElse(providers.environmentVariable("CLOJARS_USERNAME"))).orNull
                password = (providers.gradleProperty("clojarsPassword")
                    .orElse(providers.environmentVariable("CLOJARS_PASSWORD"))).orNull
            }
        }
    }
}
