(ns skein.dev-repl
  "Babashka helpers behind the `bb repl:*` tasks: launch a standalone JVM
  Clojure nREPL scoped to one module's classpath, or connect a client to the
  nREPL of a running game.

  These REPLs run outside the game, so only namespaces whose Java dependencies
  are resolvable standalone will load; the game-facing ones (FabricLoader,
  fabric-api, Minecraft, Brigadier) come alive only inside a running instance —
  connect to those with `bb repl:connect`. See each module's :note below."
  (:require [babashka.fs :as fs]
            [babashka.process :as p]
            [clojure.string :as str]))

(def ^:private versions-file "gradle/libs.versions.toml")

(defn- parse-versions
  "Reads the [versions] table of libs.versions.toml into {\"key\" \"value\"}.
  Babashka ships no TOML reader, but that table is a flat `key = \"value\"`
  list, so scanning it section-aware keeps these REPLs on the build's single
  source of truth for versions instead of duplicating them here."
  []
  (loop [lines (str/split-lines (slurp versions-file))
         section nil
         acc {}]
    (if-let [line (first lines)]
      (let [header (some-> (re-matches #"\s*\[([^\]]+)\].*" line) second)
            kv (when (= section "versions")
                 (re-matches #"\s*([\w-]+)\s*=\s*\"([^\"]+)\"\s*(?:#.*)?" line))]
        (recur (rest lines)
               (or header section)
               (if kv (assoc acc (nth kv 1) (nth kv 2)) acc)))
      acc)))

(def ^:private versions (delay (parse-versions)))

;; Maven coordinates keyed by the version alias used in libs.versions.toml, so
;; `(dep k)` reads both the group:artifact and the pinned version from one place.
(def ^:private coord
  {:clojure       "org.clojure/clojure"
   :nrepl         "nrepl/nrepl"
   :asm           "org.ow2.asm/asm"
   :sponge-mixin  "net.fabricmc/sponge-mixin"
   :malli         "metosin/malli"
   :slf4j         "org.slf4j/slf4j-api"
   :tools-deps    "org.clojure/tools.deps"
   :fabric-loader "net.fabricmc/fabric-loader"})

(defn- dep [k]
  (let [alias (name k)
        version (or (get @versions alias)
                    (throw (ex-info (str "version alias not found in " versions-file ": " alias)
                                    {:alias alias})))]
    [(symbol (coord k)) {:mvn/version version}]))

;; sponge-mixin and fabric-loader live in Fabric's Maven, not Central/Clojars.
(def ^:private fabric-repo {"fabric" {:url "https://maven.fabricmc.net/"}})

(def modules
  {"core-lib" {:port 7882
               :deps [:clojure :nrepl :asm :sponge-mixin :malli :slf4j]
               :repos fabric-repo
               :paths ["core-lib/src/main/clojure" "core-lib/src/test/clojure"]
               ;; SkeinHooks (the target of the generated bytecode) is Java in
               ;; :runtime — on the path only once it has been compiled.
               :optional-paths ["runtime/build/classes/java/main"]
               :note "skein.mixin.* loads standalone. skein.core / skein.events pull in Minecraft + fabric-api and need the game classpath (Gradle)."}
   "repl"     {:port 7881
               :deps [:clojure :nrepl :tools-deps :fabric-loader]
               :repos fabric-repo
               :paths ["repl/src/main/clojure"]
               :note "skein.repl dispatches onto game executors via FabricLoader; those resolve only inside a running game. Standalone is for editing/compiling."}
   "scripts"  {:port 7883
               :deps [:clojure :nrepl :tools-deps :fabric-loader]
               :repos fabric-repo
               :paths ["skein-scripts/src/main/clojure" "skein-scripts/src/test/clojure" "core-lib/src/main/clojure"]
               :note "config / deps / loader logic is standalone; command / core reach for fabric-api + Brigadier (the game) and need the Loom classpath."}})

(defn- sdeps
  "Builds the -Sdeps EDN string for a module, dropping optional source dirs
  that have not been produced yet."
  [{:keys [deps repos paths optional-paths]}]
  (pr-str {:deps (into {} (map dep) deps)
           :paths (into [] (filter fs/exists?) (concat paths optional-paths))
           :mvn/repos repos}))

(defn nrepl!
  "Starts a standalone headless nREPL server for `module`, writing .nrepl-port
  in the repo root so an editor can jack in. Blocks until interrupted."
  [module]
  (let [{:keys [port note] :as cfg} (or (get modules module)
                                        (throw (ex-info (str "unknown module: " module
                                                             " (known: " (str/join ", " (keys modules)) ")")
                                                        {:module module})))]
    (println (str "Standalone nREPL for " module " → 127.0.0.1:" port " (also written to .nrepl-port)"))
    (println (str "Jack in from your editor, or `bb repl:connect 127.0.0.1 " port "`. Ctrl-C to stop."))
    (when note (println (str "Note: " note)))
    (p/exec "clojure" "-Sdeps" (sdeps cfg)
            "-M" "-m" "nrepl.cmdline"
            "--port" (str port))))

(defn connect!
  "Connects an nREPL client to an already-running server — the game's REPL by
  default (dev adapter opens 127.0.0.1:7888)."
  [& args]
  (let [host (or (first args) "127.0.0.1")
        port (or (second args) "7888")]
    (println (str "Connecting nREPL client to " host ":" port))
    (p/exec "clojure" "-Sdeps" (pr-str {:deps (into {} [(dep :nrepl)])})
            "-M" "-m" "nrepl.cmdline"
            "--connect" "--host" host "--port" (str port))))
