(ns skein.dev-repl
  "Babashka helpers behind the `bb repl:*` tasks: launch a standalone JVM
  Clojure nREPL scoped to one module's classpath, or connect a client to the
  nREPL of a running game.

  These REPLs run outside the game, so only namespaces whose Java dependencies
  are resolvable standalone will load; the game-facing ones (FabricLoader,
  fabric-api, Minecraft, Brigadier) come alive only inside a running instance —
  connect to those with `bb repl:connect`. See each module's :note below."
  (:require [babashka.fs :as fs]
            [babashka.process :as p]
            [clojure.string :as str]))

(def ^:private versions-file "gradle/libs.versions.toml")

(defn- parse-versions
  "Reads the [versions] table of libs.versions.toml into {\"key\" \"value\"}.
  Babashka ships no TOML reader, but that table is a flat `key = \"value\"`
  list, so scanning it section-aware keeps these REPLs on the build's single
  source of truth for versions instead of duplicating them here."
  []
  (loop [lines (str/split-lines (slurp versions-file))
         section nil
         acc {}]
    (if-let [line (first lines)]
      (let [header (some-> (re-matches #"\s*\[([^\]]+)\].*" line) second)
            kv (when (= section "versions")
                 (re-matches #"\s*([\w-]+)\s*=\s*\"([^\"]+)\"\s*(?:#.*)?" line))]
        (recur (rest lines)
               (or header section)
               (if kv (assoc acc (nth kv 1) (nth kv 2)) acc)))
      acc)))

(def ^:private versions (delay (parse-versions)))

;; Maven coordinates keyed by the version alias used in libs.versions.toml, so
;; `(dep k)` reads both the group:artifact and the pinned version from one place.
(def ^:private coord
  {:clojure       "org.clojure/clojure"
   :nrepl         "nrepl/nrepl"
   :asm           "org.ow2.asm/asm"
   :sponge-mixin  "net.fabricmc/sponge-mixin"
   :malli         "metosin/malli"
   :slf4j         "org.slf4j/slf4j-api"
   :tools-deps    "org.clojure/tools.deps"
   :fabric-loader "net.fabricmc/fabric-loader"})

(defn- dep [k]
  (let [alias (name k)
        version (or (get @versions alias)
                    (throw (ex-info (str "version alias not found in " versions-file ": " alias)
                                    {:alias alias})))]
    [(symbol (coord k)) {:mvn/version version}]))

;; sponge-mixin and fabric-loader live in Fabric's Maven, not Central/Clojars.
(def ^:private fabric-repo {"fabric" {:url "https://maven.fabricmc.net/"}})

(def modules
  {"core-lib" {:port 7882
               :deps [:clojure :nrepl :asm :sponge-mixin :malli :slf4j]
               :repos fabric-repo
               :paths ["core-lib/src/main/clojure" "core-lib/src/test/clojure"]
               ;; SkeinHooks (the target of the generated bytecode) is Java in
               ;; :runtime — on the path only once it has been compiled.
               :optional-paths ["runtime/build/classes/java/main"]
               ;; The deobfuscated game jar and its libraries, as the Gradle
               ;; build resolves them (written by :example-mod:exportGameClasspath).
               ;; With it on the path the namespaces that only need game *classes*
               ;; — the coercions, skein.codec and its Mojang Codec — load and can
               ;; be exercised here; the ones that need a *running* game still
               ;; cannot.
               :optional-classpath-file "example-mod/build/skein-game-classpath.txt"
               :note "skein.mixin.* and (once the game classpath file exists) the L1/codec namespaces load standalone. skein.core / skein.events pull in fabric-api and a running game."}
   "repl"     {:port 7881
               :deps [:clojure :nrepl :tools-deps :fabric-loader]
               :repos fabric-repo
               :paths ["repl/src/main/clojure"]
               :note "skein.repl dispatches onto game executors via FabricLoader; those resolve only inside a running game. Standalone is for editing/compiling."}
   "scripts"  {:port 7883
               :deps [:clojure :nrepl :tools-deps :fabric-loader]
               :repos fabric-repo
               :paths ["skein-scripts/src/main/clojure" "skein-scripts/src/test/clojure" "core-lib/src/main/clojure"]
               :note "config / deps / loader logic is standalone; command / core reach for fabric-api + Brigadier (the game) and need the Loom classpath."}})

(defn- classpath-file-entries
  "The classpath roots listed in a file the Gradle build exports, or nothing
  when the build has not produced it yet."
  [path]
  (when (and path (fs/exists? path))
    (->> (str/split-lines (slurp path))
         (remove str/blank?)
         (filter fs/exists?))))

(defn- sdeps
  "Builds the -Sdeps EDN string for a module, dropping optional source dirs
  (and an exported classpath file) that have not been produced yet."
  [{:keys [deps repos paths optional-paths optional-classpath-file]}]
  (pr-str {:deps (into {} (map dep) deps)
           :paths (into (into [] (filter fs/exists?) (concat paths optional-paths))
                        (classpath-file-entries optional-classpath-file))
           :mvn/repos repos}))

(def ^:private min-game-jdk
  "The game's classes are Java 25 bytecode; an older JVM cannot even load them."
  25)

(defn- game-jdk-home
  "A JDK new enough to load the game classes: the toolchain JDK Gradle has
  already provisioned for this build (~/.gradle/jdks). nil when none is there —
  the REPL then still starts, just without the game jars being loadable."
  []
  (->> (fs/glob (fs/path (fs/home) ".gradle" "jdks") "*/jdk-*/Contents/Home")
       (keep (fn [home]
               (when-some [major (some-> (re-find #"jdk-(\d+)" (str home)) second parse-long)]
                 (when (>= major min-game-jdk) [major (str home)]))))
       (sort-by first)
       last
       second))

(defn nrepl!
  "Starts a standalone headless nREPL server for `module`, writing .nrepl-port
  in the repo root so an editor can jack in. Blocks until interrupted."
  [module]
  (let [{:keys [port note optional-classpath-file] :as cfg}
        (or (get modules module)
            (throw (ex-info (str "unknown module: " module
                                 " (known: " (str/join ", " (keys modules)) ")")
                            {:module module})))
        ;; Only the modules that put the game jars on the path need the newer
        ;; JVM; everything else runs on whatever java is on PATH.
        game-jdk (when (seq (classpath-file-entries optional-classpath-file)) (game-jdk-home))]
    (println (str "Standalone nREPL for " module " → 127.0.0.1:" port " (also written to .nrepl-port)"))
    (println (str "Jack in from your editor, or `bb repl:connect 127.0.0.1 " port "`. Ctrl-C to stop."))
    (when note (println (str "Note: " note)))
    (when (and (some? optional-classpath-file) (nil? game-jdk) (seq (classpath-file-entries optional-classpath-file)))
      (println (str "Note: no JDK " min-game-jdk "+ found under ~/.gradle/jdks — the game classes on the path"
                    " will fail to load. Run a Gradle build once so the toolchain is provisioned.")))
    ;; Both JAVA_HOME and PATH: a version-manager shim earlier on PATH would
    ;; otherwise win over JAVA_HOME and hand the REPL an older JVM.
    (p/exec {:extra-env (when game-jdk
                          {"JAVA_HOME" game-jdk
                           "PATH" (str game-jdk "/bin" fs/path-separator (System/getenv "PATH"))})}
            "clojure" "-Sdeps" (sdeps cfg)
            "-M" "-m" "nrepl.cmdline"
            "--port" (str port))))

(defn connect!
  "Connects an nREPL client to an already-running server — the game's REPL by
  default (dev adapter opens 127.0.0.1:7888)."
  [& args]
  (let [host (or (first args) "127.0.0.1")
        port (or (second args) "7888")]
    (println (str "Connecting nREPL client to " host ":" port))
    (p/exec "clojure" "-Sdeps" (pr-str {:deps (into {} [(dep :nrepl)])})
            "-M" "-m" "nrepl.cmdline"
            "--connect" "--host" host "--port" (str port))))
