(ns skein-example.mixin
  "Mixin logic as data: `defmixin` declares the injection point and the
  handler in one form. The target is verified against the real game
  classes at compile time (a typo would fail this very namespace's AOT),
  the mixin class is generated by the build — no Java stub, no
  handwritten mixins json, no fabric.mod.json entry. The handler is a
  plain defn behind a var: redefine it from the REPL and the very next
  server tick runs the new body."
  (:require [skein.mixin :refer [defmixin]]))

(def tick-count
  "Server tick counter — incremented from the generated HEAD inject into
  MinecraftServer.tickServer."
  (atom 0))

(defmixin server-mixin
  {:target net.minecraft.server.MinecraftServer}
  (inject {:at :head}
    (tickServer [_server _have-time _ci]
      (swap! tick-count inc))))
